version: '3.7'
services:
  db:
    image: postgres
    env_file: .env
    ports:
      - '5432:5432'
    networks:
      - investment-bot
  app:
    build: ./
    ports:
      - '4000:4000'
    command: npm run start:dev
    networks:
      - investment-bot
    links:
      - db
    depends_on:
      - db
    volumes:
      - ./:/home/node/
      - /home/node/node_modules
networks:
  investment-bot:
    driver: bridge
